apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
  namespace: k8s-wordpress-project
spec:
  ports:
  - port: 25000
    protocol: TCP
    targetPort: 80
    nodePort: 30005
  selector:
    app: wordpress
  type: NodePort
status:
  loadBalancer: {}
