apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql
  namespace: k8s-wordpress-project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 2Gi

