apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-mysql
  name: wordpress-mysql
  namespace: k8s-wordpress-project
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress-mysql
  type: ClusterIP
status:
  loadBalancer: {}
