apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-mysql
  name: wordpress-mysql
  namespace: k8s-wordpress-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env: 
              - name: MYSQL_RANDOM_ROOT_PASSWORD
                value: '1'
              - name: MYSQL_USER
                value: wordpress
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                     name: wordpress-mysql-secret
                     key: wordpress
              - name: MYSQL_DATABASE
                value: wordpress
        volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        resources: {}
      volumes:
      - name: mysql-persistent-storage
        hostPath:
              path: /data/mysql
status: {}
